
services:
  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quejas_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo:5
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  usuario_service:
    build: ./usuario_service
    ports:
      - "8001:8000"
    depends_on:
      - postgres

  quejas_web_service:
    build: ./quejas_web_service
    ports:
      - "8002:8000"
    depends_on:
      - mongo

  quejas_oficina_service:
    build: ./quejas_oficina_service
    ports:
      - "8003:8000"
    depends_on:
      - postgres

  reportes_service:
    build: ./reportes_service
    ports:
      - "8004:8000"
    depends_on:
      - mongo
      - postgres

volumes:
  pg_data:
  mongo_data:
